### ISSUE TITLE
[FEATURE]: support configServer V2

### ISSUE THREAD

**Issue by quzard** [alibaba/loongcollector#1621]
# 当前进度
- [x] https://github.com/alibaba/ilogtail/discussions/1491
- [x] https://github.com/alibaba/ilogtail/pull/1516
- [x] https://github.com/alibaba/ilogtail/pull/1564
- [x] https://github.com/alibaba/ilogtail/pull/1592  - 该 PR 改造了 ConfigWatcher.cpp，同时支持 ProcessConfig 和 PipelineConfig，并提交了一个基础的ProcessConfigManage
# TODO
- [ ] [支持v2版本client](https://github.com/alibaba/ilogtail/pull/1633)
- [ ] ProcessConfigManage机制完善，支持配置加载、卸载和应用
